# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on: push
name: Test, Build and Release apk
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.6'
      # Get flutter dependencies.
      - run: flutter pub get

      # Check for any formatting issues in the code.
#      - run: flutter format --set-exit-if-changed .

      # Statically analyze the Dart code for any errors.
      - run: flutter analyze .

      # Build apk.
      - run: flutter build apk

      - name: APK artifact
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: build/app/outputs/apk/release/app-release.apk

      - name: Show APK
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "build/app/outputs/apk/release/app-release.apk"
          token: ${{ secrets.CICD }}
          tag: v1.0.3
#      - uses: ncipollo/release-action@v1
#        with:
#          name: release-apk
#          path: build/app/outputs/apk/release/app-release.apk
#          token: ${{ secrets.CICD }}
#          tag: v1.0.1
